#!/usr/bin/env bash

fatal()
{
	echo "$1"
	exit 1
}

if [[ -z "$1" ]] ; then
	git describe --tags --long --exclude 'v*' | sed -s 's/-.*//'
else
	git commit -a -m "newver $1" || fatal 'git commit failed'
	git tag "$1" || fatal 'git tag failed'
	git push origin "$1" || fatal 'git push failed'
fi
#.

