#!/usr/bin/env bash

fatal()
{
        echo "$1"
        exit 1
}

[[ -n $(git status --porcelain) ]] && fatal 'you should commmit before'

git push || fatal 'push failed'
A=$(./scmrev | sed -r 's/-g.*//')
git tag "$A" || fatal 'tag failed'
git push origin "refs/tags/$A" || fatal 'push tags failed'
#.
