#!/usr/bin/env bash

RP=$(realpath "$0")
D=$(dirname "$RP")

B=$(git branch --show-current 2> /dev/null)
[[ -z "$B" ]] && exit 1
if [[ "$B" == 'main' ]] ; then
    C=''
else
    C="-$B"
fi
T=$(git describe --always --tags --long --exclude '*-*' --match '[0-9].*')
TB=$(echo "$T" | sed -r 's/-.*//')
TK=$(<"$D/basetag")
[[ "$TB" == "$TK" ]] && echo "$T$C" || echo "! $TB <> $TK"
#.
